import streamlit as st
import requests
import re
import pandas as pd
import altair as alt
from fpdf import FPDF

# --- Helper: PDF Generator ---
def create_pdf(user_input, response_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Tanit Health AI - Clinical Report", ln=1, align='C')
    
    # User Query
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Subject: {user_input}", ln=1, align='L')
    pdf.ln(10)
    
    # Body 
    clean_text = response_text.replace("*", "").encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, txt=clean_text)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, txt="Generated by AI Agent. Consult a Doctor.", ln=1, align='C')
    
    return pdf.output(dest='S').encode('latin-1', 'replace')

# --- Page Config ---
st.set_page_config(page_title="Tanit Health AI", page_icon="🩺", layout="centered")

# --- CSS  ---
st.markdown("""
    <style>
    .stChatMessage { 
        background-color: #ffffff; 
        border-radius: 15px; 
        padding: 15px; 
        box-shadow: 0 4px 6px rgba(0,0,0,0.05); 
        margin-bottom: 10px;
    }
    .stButton button { 
        border-radius: 20px; 
        font-weight: bold;
    }
    h1 { color: #2C3E50; }
    </style>
""", unsafe_allow_html=True)

# --- Sidebar ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3063/3063176.png", width=80)
    st.title("Tanit Health")
    st.caption("AI-Powered Medical Triage")
    st.markdown("---")
    st.success("System Status: **Online** 🟢")
    st.markdown("---")
    st.markdown("⚡ **Powered by:**")
    st.info("`Llama-3.3-70b-Versatile`")

# --- Header ---
st.title("🩺 Medical Assistant Agent")
st.markdown("Describe symptoms below. The **Supervisor Agent** will validate clinical data before answering.")

# --- Chat State ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- Render Chat History ---
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        
        if "chart_data" in message:
            st.markdown("---")
            st.caption("📊 **Clinical Confidence Score**")
            
            # Render the nice Altair chart
            chart = alt.Chart(message["chart_data"]).mark_bar(
                cornerRadiusTopRight=10, 
                cornerRadiusBottomRight=10,
                height=20
            ).encode(
                x=alt.X('Confidence', title='Match Probability (0-1)', scale=alt.Scale(domain=[0, 1])),
                y=alt.Y('Disease', sort='-x', title=None),
                color=alt.Color('Confidence', scale=alt.Scale(scheme='viridis'), legend=None),
                tooltip=['Disease', 'Confidence']
            ).properties(height=200)
            
            st.altair_chart(chart, use_container_width=True)

if prompt := st.chat_input("E.g., 'I have high fever, chills, and nausea.'"):
    
    # 1. Show User Message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # 2. Generate Response
    with st.chat_message("assistant"):
        with st.spinner("🏥 Intern is querying Neo4j... Supervisor is reviewing..."):
            try:
                # Call Backend
                response = requests.post("http://localhost:8000/chat", json={"query": prompt})
                
                if response.status_code == 200:
                    data = response.json()
                    final_answer = data["response"]
                    reasoning_log = data["reasoning"]

                    # --- A. Reasoning Expander ---
                    with st.expander("🧠 View Agent Reasoning Process", expanded=False):
                        for step in reasoning_log:
                            if step["type"] == "tool_call":
                                st.info(f"🛠️ **Action:** `{step['content']}`")
                            elif step["type"] == "tool_result":
                                st.code(step['content'], language="markdown")
                            elif step["type"] == "intern_draft":
                                st.warning(f"📝 **Intern's Draft:**\n{step['content']}")

                    # --- B. The Text Answer ---
                    st.markdown(final_answer)

                    # --- C. Data Extraction for Chart ---
                    diseases = []
                    scores = []
                    for step in reasoning_log:
                        if step["type"] == "tool_result":
                            # Extract all matches
                            matches = re.findall(r"Disease Found: (.*?) \(Similarity: (.*?)\)", step["content"])
                            for match in matches:
                                diseases.append(match[0])
                                scores.append(float(match[1]))
                    
                    chart_df = None
                    if diseases:
                        chart_df = pd.DataFrame({"Disease": diseases, "Confidence": scores})
                        
                        # --- D. The Chart (Bottom) ---
                        st.markdown("---")
                        st.caption("📊 **Clinical Confidence Score (Vector Analysis)**")
                        
                        chart = alt.Chart(chart_df).mark_bar(
                            cornerRadiusTopRight=10, 
                            cornerRadiusBottomRight=10,
                            height=20 # Slender bars
                        ).encode(
                            x=alt.X('Confidence', title='Match Probability (0-1)'),
                            y=alt.Y('Disease', sort='-x', title=None), # Sorted by confidence
                            color=alt.Color('Confidence', scale=alt.Scale(scheme='viridis'), legend=None),
                            tooltip=['Disease', 'Confidence']
                        ).properties(height=200)
                        
                        st.altair_chart(chart, use_container_width=True)

                    # --- E. Download Button ---
                    pdf_bytes = create_pdf(prompt, final_answer)
                    st.download_button(
                        label="📄 Download Clinical Report (PDF)",
                        data=pdf_bytes,
                        file_name="tanit_report.pdf",
                        mime="application/pdf"
                    )

                    # Save to history
                    msg_data = {"role": "assistant", "content": final_answer}
                    if chart_df is not None:
                        msg_data["chart_data"] = chart_df
                    st.session_state.messages.append(msg_data)

                else:
                    st.error(f"Backend Error: {response.text}")

            except Exception as e:
                st.error(f"Connection Error: {e}")
                st.info("Ensure `python api.py` is running.")